version: '3'

services:
  LuftdatenBoxStarter:
    image: s3ler/luftdatenboxstart
    networks:
      - frontend
    links:
      - Node-Red:node-red
      - Grafana:grafana
      - Chronograf:chronograf
    ports:
      - 80:80

  MQTT-Broker:
    image: fstehle/rpi-mosquitto
    networks:
      - frontend
    ports:
      - 1883:1883
      - 9001:9001

  Node-Red:
    image: nodered/node-red-docker:rpi
    networks:
      - frontend
      - influxdb
    links:
      - InfluxDB:influxdb
      - MQTT-Broker:mqtt-broker
    ports:
      - 1880:1880

  Grafana:
    image: s3ler/grafana-plugin
    networks:
      - frontend
      - influxdb
    links:
      - InfluxDB:influxdb
    ports:
      - 3000:3000

  InfluxDB:
    image: arm32v7/influxdb
    networks:
      - influxdb

  Chronograf:
    image: arm32v7/chronograf
    networks:
      - influxdb
      - frontend
    ports:
      - 8888:8888
    links:
      - InfluxDB:influxdb
    command:
      - --influxdb-url=http://influxdb:8086

networks:
  frontend:
  influxdb:

