version: '3'

services:
  Proxy:
    image: amd64/nginx
    networks:
      - frontend
    links:
      - LuftdatenBoxStarter:starterbox
      - Node-Red:nodered
    volumes:
      - certificate:/etc/nginx/certificate
      - privatekey:/etc/nginx/privatekey
      - ./default:/etc/nginx/conf.d/default.conf
      - ./nodered:/etc/nginx/conf.d/nodered.conf
      - ./htpasswd/htpasswd:/etc/nginx/htpasswd/.htpasswd
    ports:
      - 80:80
      - 301:301
      - 443:443

  LuftdatenBoxStarter:
    image: s3ler/luftdatenboxstart
    networks:
      - frontend

  Node-Red:
    image: nodered/node-red-docker
    networks:
      - frontend
      - influxdb
    volumes:
      - noderedv:/data/flows



networks:
  frontend:
  influxdb:

volumes:
  certificate:
    external:
      name: ssl_certificate
  privatekey:
    external:
      name: ssl_privatekey

  grafanav:
  noderedv:
