version: '3'

services:
  CreateSelfSignedSSLCertificateAndPrivateKey:
    build:
      context: .
      dockerfile: Dockerfile
    image: s3ler/createcertandprivkey:latest
    volumes:
      - ./sslConfig.sh:/sslConfig.sh
      - ca:/etc/ca-certificates/selfsignedca
      - ca:/etc/ssl/private/selfsignedca
      - proxy:/etc/ca-certificates/proxy
      - proxy:/etc/ssl/private/proxy
      - mqtt:/etc/ca-certificates/mqtt
      - mqtt:/etc/ssl/private/mqtt

volumes:
  ca:
  proxy:
  mqtt:


