version: '3'

services:
  CreateSelfSignedSSLCertificateAndPrivateKey:
    build:
      context: .
      dockerfile: Dockerfile
    image: s3ler/createcertandprivkey:latest
    volumes:
      - ./certificate.conf:/certificate.conf
      - certs:/etc/ssl/certs
      - private:/etc/ssl/private
      - csr:/etc/ssl/csr

volumes:
  certs:
  private:
  csr:


