version: '3'

services:
  MQTT-Broker:
    image: amd64/eclipse-mosquitto
    restart: always
    networks:
      - frontend
    volumes:
      - ./Mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ca:/mosquitto/ca/
      - mqtt:/mosquitto/certs/
      - mqtt:/mosquitto/private/
    ports:
      - 1883:1883
      - 8883:8883
      - 9001:9001

  Proxy:
    image: amd64/nginx
    restart: always
    networks:
      - frontend
    depends_on:
      - LuftdatenBoxStarter
    links:
      - LuftdatenBoxStarter:starterbox
      - Node-Red:nodered
      - Grafana:grafana
      - Chronograf:chronograf
      - Portainer:portainer
    volumes:
      - proxy:/etc/nginx/certs/
      - proxy:/etc/nginx/private/
      - ./Proxy/conf.d/:/etc/nginx/conf.d/
      - ./Proxy/htpasswd/htpasswd:/etc/nginx/htpasswd/.htpasswd
    ports:
      - 80:80
      - 301:301
      - 443:443

  LuftdatenBoxStarter:
    image: s3ler/luftdatenboxstart
    restart: always
    networks:
      - frontend
    links:
      - Node-Red:node-red
      - Grafana:grafana
      - Chronograf:chronograf
      - Portainer:portainer

  Portainer:
    image: portainer/portainer:latest
    restart: always
    networks:
      - frontend
    volumes:
      - portainerv:/opt/portainer
      - '/var/run/docker.sock:/var/run/docker.sock'
    expose:
      - 9000
    command:
      - --no-auth

  Node-Red:
    image: nodered/node-red-docker
    restart: always
    networks:
      - frontend
      - influxdb
    volumes:
      - noderedv:/data/flows
    links:
      - InfluxDB:influxdb
      - MQTT-Broker:mqtt-broker

  Grafana:
    image: s3ler/grafana-plugin
    restart: always
    networks:
      - frontend
      - influxdb
    volumes:
      - grafanav:/var/lib/grafana
    links:
      - InfluxDB:influxdb
    environment:
      - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s:/grafana
      - GF_USERS_DEFAULT_THEME=light

  InfluxDB:
    image: amd64/influxdb:alpine
    restart: always
    networks:
      - influxdb
    volumes:
      - influxdbv:/var/lib/influxdb

  Chronograf:
    image: amd64/chronograf:alpine
    restart: always
    networks:
      - influxdb
      - frontend
    links:
      - InfluxDB:influxdb
    command:
      - --influxdb-url=http://influxdb:8086
      - --basepath=/chronograf

networks:
  frontend:
  influxdb:

volumes:
  ca:
    external:
      name: ssl_ca
  mqtt:
    external:
      name: ssl_mqtt
  proxy:
    external:
      name: ssl_proxy

  grafanav:
  noderedv:
  influxdbv:
  portainerv:
