version: '3'

services:
  MQTT-Broker:
    image: amd64/eclipse-mosquitto
    networks:
      - frontend
    ports:
      - 1883:1883
      - 9001:9001

  Proxy:
    image: amd64/nginx
    networks:
      - frontend
    links:
      - LuftdatenBoxStarter:starterbox
      - Node-Red:nodered
      - Grafana:grafana
      - Chronograf:chronograf
    volumes:
      - certs:/etc/nginx/certs/
      - private:/etc/nginx/private/
      - ./Proxy/conf.d/:/etc/nginx/conf.d/
      - ./Proxy/htpasswd/htpasswd:/etc/nginx/htpasswd/.htpasswd
    ports:
      - 80:80
      - 301:301
      - 443:443

  LuftdatenBoxStarter:
    image: s3ler/luftdatenboxstart
    networks:
      - frontend
    links:
      - Node-Red:node-red
      - Grafana:grafana
      - Chronograf:chronograf

  Node-Red:
    image: nodered/node-red-docker
    networks:
      - frontend
      - influxdb
    volumes:
      - noderedv:/data/flows
    links:
      - InfluxDB:influxdb
      - MQTT-Broker:mqtt-broker

  Grafana:
    image: s3ler/grafana-plugin
    networks:
      - frontend
      - influxdb
    volumes:
      - grafanav:/var/lib/grafana
    links:
      - InfluxDB:influxdb

  InfluxDB:
    image: amd64/influxdb:alpine
    networks:
      - influxdb
    volumes:
      - influxdbv:/var/lib/influxdb

  Chronograf:
    image: amd64/chronograf:alpine
    networks:
      - influxdb
      - frontend
    links:
      - InfluxDB:influxdb
    command:
      - --influxdb-url=http://influxdb:8086

networks:
  frontend:
  influxdb:

volumes:
  certs:
    external:
      name: ssl_certs
  private:
    external:
      name: ssl_private
  csr:
    external:
      name: ssl_csr

  grafanav:
  noderedv:
  influxdbv:
