version: '3'

services:
  MQTT-Broker:
    image: amd64/eclipse-mosquitto
    networks:
      - frontend
    volumes:
      - ./Mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ca:/mosquitto/ca/
      - mqtt:/mosquitto/certs/
      - mqtt:/mosquitto/private/
    ports:
      - 1883:1883
      - 8883:8883
      - 9001:9001

  Proxy:
    image: amd64/nginx
    networks:
      - frontend
    links:
      - LuftdatenBoxStarter:starterbox
      - Node-Red:nodered
      - Grafana:grafana
      - Chronograf:chronograf
    volumes:
      - proxy:/etc/nginx/certs/
      - proxy:/etc/nginx/private/
      - ./Proxy/conf.d/:/etc/nginx/conf.d/
      - ./Proxy/htpasswd/htpasswd:/etc/nginx/htpasswd/.htpasswd
    ports:
      - 80:80
      - 301:301
      - 443:443

  LuftdatenBoxStarter:
    image: s3ler/luftdatenboxstart
    networks:
      - frontend
    links:
      - Node-Red:node-red
      - Grafana:grafana
      - Chronograf:chronograf

  Node-Red:
    image: nodered/node-red-docker
    networks:
      - frontend
      - influxdb
    volumes:
      - noderedv:/data/flows
    links:
      - InfluxDB:influxdb
      - MQTT-Broker:mqtt-broker

  Grafana:
    image: grafana:latest-with-plugins
    build:
      context: ${PWD}/grafana/packaging/docker/custom/
      dockerfile: ${PWD}/grafana/packaging/docker/custom/Dockerfile
      args:
        - GRAFANA_VERSION=latest
        - "GF_INSTALL_PLUGINS=GF_INSTALL_PLUGINS=
                             grafana-worldmap-panel,
                             grafana-clock-panel,
                             grafana-piechart-panel,
                             satellogic-3d-globe-panel,
                             ryantxu-ajax-panel,
                             btplc-alarm-box-panel,
                             novalabs-annotations-panel,
                             michaeldmoore-annunciator-panel,
                             yesoreyeram-boomtable-panel,
                             digiapulssi-breadcrumb-panel,
                             digrich-bubblechart-panel,
                             neocat-cal-heatmap-panel,
                             petrslavotinek-carpetplot-panel,
                             briangann-gauge-panel,
                             briangann-datatable-panel,
                             jdbranham-diagram-panel,
                             natel-discrete-panel,
                             citilogics-geoloop-panel,
                             savantly-heatmap-panel,
                             mtanda-heatmap-epoch-panel,
                             mtanda-histogram-panel,
                             natel-influx-admin-panel,
                             digiapulssi-organisations-panel,
                             zuburqan-parity-report-panel,
                             btplc-peak-report-panel,
                             bessler-pictureit-panel,
                             natel-plotly-panel,
                             snuids-radar-panel,
                             blackmirror1-singlestat-math-panel,
                             blackmirror1-statusbygroup-panel,
                             btplc-status-dot-panel,
                             vonage-status-panel,
                             flant-statusmap-panel,
                             marcuscalidus-svg-panel,
                             snuids-trafficlights-panel,
                             smartmakers-trafficlight-panel,
                             btplc-trend-box-panel,
                             fatcloud-windrose-panel"
    networks:
      - frontend
      - influxdb
    volumes:
      - grafanav:/var/lib/grafana
    links:
      - InfluxDB:influxdb
    environment:
      - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s:/grafana

  InfluxDB:
    image: amd64/influxdb:alpine
    networks:
      - influxdb
    volumes:
      - influxdbv:/var/lib/influxdb

  Chronograf:
    image: amd64/chronograf:alpine
    environment:
      BASE_PATH: /chronograf
      INFLUXDB_URL: http://influxdb:8086
    networks:
      - influxdb
      - frontend
    links:
      - InfluxDB:influxdb
    ports:
      - 8888:8888


networks:
  frontend:
  influxdb:

volumes:
  ca:
    external:
      name: ssl_ca
  mqtt:
    external:
      name: ssl_mqtt
  proxy:
    external:
      name: ssl_proxy

  grafanav:
  noderedv:
  influxdbv:
